services:
  backend:
    restart: on-failure
    build: ./backend
    hostname: backend
  frontend:
    restart: on-failure
    build: ./frontend
    hostname: frontend
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
